name: Publish dbt Docs to Netlify

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dbt
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      # Step 4: Create the profiles.yml file
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          ibis:
            target: dev
            outputs:
              dev:
                type: postgres
                host: \"$DB_HOST\"
                user: \"$DB_USER\"
                password: \"$DB_PASSWORD\"
                port: 5432
                dbname: \"$DB_NAME\"
                schema: public
                threads: 1
          " > ~/.dbt/profiles.yml
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      # Step 5: Run dbt commands
      - name: Run dbt commands
        run: |
          dbt deps  # Install dbt packages
          dbt debug  # Validate the setup
          dbt docs generate
